version: "3"
services:
  simple_php:
    build: .
    image: simple_php_dock
    ports:
      - 8080:80
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
    ports:
      - 5433:5432

     